version: "3.8"

services:
  express:
    image: kolmio3/express-app
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock
    container_name: watchtower
